backend:
  name: github
  repo: davedub/parkgno-a

media_folder: static/assets
public_folder: assets

collections:
  - label: "Pages"
    name: "Page"
    folder: content/pages
    create: true
    fields:
      - { name: category, label: Category, widget: string }
      - { name: path, label: Path }
      - { name: title, label: Title, widget: string }
      - { name: intro, label: Intro, widget: markdown }
      - { name: body, label: Body, widget: markdown }
  - label: "Documents"
    name: "Document"
    folder: content/documents
    create: true
    fields:
      - { name: category, label: Category, widget: string }
      - { name: path, label: Path }
      - { name: title, label: Title, widget: string }
      - { name: intro, label: Intro, widget: markdown }
      - { name: body, label: Body, widget: markdown }
  - label: "Members"
    name: "Member"
    folder: content/members
    create: true
    fields:
      - { name: category, label: Category, widget: string }
      - { name: path, label: Path }
      - { name: title, label: Title, widget: string }
      - { name: name, label: Name, widget: string }
      - { name: address, label: Address, widget: markdown }
      - { name: email, label: email, widget: string }
      - { name: telephone, label: telephone, widget: string }
