backend:
  name: github
  repo: davedub/parkgno

media_folder: static/assets
public_folder: assets

collections:
  - label: "Pages"
    name: "pages"
    folder: pages
    create: true
    fields:
      - {name: path, label: Path}
      - {name: title, label: Title, widget: string}
      - {name: intro, label: Intro, widget: markdown}
      - {name: body, label: Body, widget: markdown }
      - {label: Location, name: location, widget: map}
  - label: "Documents"				
    name: "Document"
    folder: documents
    create: true
    fields:				
      - {name: path, label: Path}
      - {name: title, label: Title, widget: string}
      - {name: intro, label: Intro, widget: markdown}
      - {name: body, label: Body, widget: markdown }
  - label: "Members"				
    name: "Member"
    folder: members
    create: true
    fields:				
      - { name: path, label: Path }
      - {name: title, label: Title, widget: string}
      - {name: name, label: Name, widget: string}
      - {name: address, label: Address, widget: markdown}
      - {name: email, label: email, widget: string }
      - {name: telephone, label: telephone, widget: string }